lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    user_identity_field: sub
    token_ttl: null

    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: HS256

    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
